### ISSUE TITLE
Game compatibility from my testing

### ISSUE THREAD

**Issue by Adamillo** [wheremyfoodat/Panda3DS#110]
I'll try to test as many games as possible

- Donkey Kong Country Returns 3D gets stuck in black screen at boot
- Luigi's Mansion gets stuck in black screen at boot (exclusive to PAL version)
- Sonic Boom: Shattered Crystal gets stuck in black screen at boot after the ring animation
- Sonic Boom: Fire & Ice gets stuck in black screen at boot after the ring animation
- Sonic Lost World gets stuck in black screen at boot
- Rayman Origins gets stuck in black screen at boot
- Kirby's Blowout Blast gets ingame with minor graphical issues
- Kirby Fighters Deluxe gets ingame with minor graphical issues
- Dedede's Drum Dash Deluxe gets ingame with minor graphical glitches
- Sonic Generations gets ingame with minor graphical issues
- Luigi's Mansion 2 gets ingame with major graphical issues
- Kirby Battle Royale crashes with [FATAL] Unimplemented 8-bit write, addr: 00000000, val: 58
- Kirby's Extra Epic Yarn crashes with [FATAL] Unimplemented svc: 3C @ 00104550
- Kirby Planet Robobot crashes with [FATAL] FS service requested. Command: 08520100
- Mario & Luigi Dream Team Bros crashes with [FATAL] LDR::RO service requested. Command: 000402C2
- Mario & Luigi Paper Jam Bros crashes with [FATAL] Thrown fatal error
- The 2 Mario & Luigi remakes crash with [FATAL] LDR::RO service requested. Command: 000902C2
- Paper Mario Sticker Star crashes with [FATAL] Thrown fatal error
- Ultimate NES Remix crashes with [FATAL] Thrown fatal error
- Yo-Kai Watch crashes with [FATAL] WaitSynchronizationN: Bad object handle FFFF8008

**Comment by KostaSaizo7** [comment]
Tested with [c8f4ec2](https://github.com/wheremyfoodat/Panda3DS/commit/c8f4ec2a11a309bddb86278677a47669e77d3393)

Pokemon Crystal VC	[FATAL] Allocated shared memory block twice. Is this allowed?
Crashmo			[FATAL] GPU service requested. Command: 00190000
Pokemon Dream Radar	[Warning] ControlMemory: unknown operation 1 & [FATAL] Unimplemented svc: 1A @ 00116DBC
Legend of Zelda Majoras Mask [Warning] Game is initializing IR:USER. If it explodes, this is probably why
Super Mario 3D Land Hangs in the menu no error
Monster Hunter 3 Ultimate [Warning] Game is initializing IR:USER. If it explodes, this is probably why
Phoenix Wright: Ace Attorney - Dual Destinies [FATAL] Unimplemented svc: 1A @ 0010E4BC
Pokédex 3D Pro [Warning] [GSP::GPU VaddrToPaddr] Unknown virtual address 09183820 & [FATAL] Unimplemented PICA instruction 0E000B07 (Opcode = 03)
Metroid Samus Returns [Warning] GSP::GPU::TriggerTextureCopy (unimplemented)
Super Smash Bros. [FATAL] Read from NCCH's non-RomFS & non-exeFS section!
Tomodachi Life [FATAL] BOSS service requested. Command: 00080002
VVVVVV [FATAL] Thrown fatal error

**Comment by ArbestRiAgain** [comment]
New Super Mario Bros. 2 runs at full speed with no issues asides from no audio.

**Comment by georgemoralis** [comment]
Resident Evil - The Mercenaries 3D, Resident Evil - Revelations   black screen

**Comment by KostaSaizo7** [comment]
Resident Evil - Revelations black screen and [FATAL] SaveData::GetFreeBytes unimplemented

**Comment by georgemoralis** [comment]
> Resident Evil - Revelations black screen and [FATAL] SaveData::GetFreeBytes unimplemented

why this didn't get delete?

**Comment by KostaSaizo7** [comment]
Animal Crossing - New Leaf - Welcome Amiibo [FATAL] LDR::RO service requested. Command: 000902C2

**Comment by KostaSaizo7** [comment]
Detective Pikachu [FATAL] Failed to find paddr

**Comment by ArbestRiAgain** [comment]
I'm also making a unofficial compatibility list on Google Sheets here: https://docs.google.com/spreadsheets/d/1nWZTzfaMPkZdyhqHEawMRBaP0qSMmQdxrVfAbgapYrM/edit?usp=sharing

**Comment by wheremyfoodat** [comment]
Hmm, haven't tried MK7 US, will in a sec

**Comment by wheremyfoodat** [comment]
@ArbestRiAgain Boots for me, just has a hefty wait until the game loads
![image](https://github.com/wheremyfoodat/Panda3DS/assets/44909372/56cb1974-2e98-4980-a458-34b833f3f3ab)

**Comment by wheremyfoodat** [comment]
I will implement OS timers soon so the SVC 1A problems should go away

**Comment by wheremyfoodat** [comment]
re: Samus Returns
It boots but the graphics are not getting displayed on screen because it does funny render-to-texture tricks

**Comment by wheremyfoodat** [comment]
@ArbestRiAgain also make sure you have the shader JIT enabled, will help with performance a lot

**Comment by ArbestRiAgain** [comment]
> @ArbestRiAgain also make sure you have the shader JIT enabled, will help with performance a lot

How do I enable it?

**Comment by wheremyfoodat** [comment]
@ArbestRiAgain open config.toml while the emu is not running at all. Set the shaderJITEnabled field to true instead of false.

**Comment by wheremyfoodat** [comment]
I will make it on by default for future builds

**Comment by wheremyfoodat** [comment]
re: LM1
Seems to work fine on my side

![image](https://github.com/wheremyfoodat/Panda3DS/assets/44909372/b487f229-8d41-4a0d-b15f-bd03ca89999d)
![image](https://github.com/wheremyfoodat/Panda3DS/assets/44909372/eb900b21-6cd8-49da-969a-97ee4ceecd94)

**Comment by LaReunion974** [comment]
about Super Smash Bros it shows 

[FATAL] srv: GetServiceHandle with unknown service news:u

![image](https://github.com/wheremyfoodat/Panda3DS/assets/102532446/0f606264-c212-4014-ad92-bade178e9a20)

**Comment by LaReunion974** [comment]
monster hunter 4 ultimate

[FATAL] Failed to find paddr

**Comment by LaReunion974** [comment]
Super Mario Maker for Nintendo 3DS (Europe) > [FATAL] Unimplemented 32-bit write, addr: 00000000, val: 00000000

Pokemon Ultra Sun (Europe) > stuck on black screen

Pokemon X (Europe) > don't boot with error
Read from user time offset field in NAND. TODO: What is this
[FATAL] Unimplemented GetFormatInfo for ExtSaveData::SDMC archive

Pokemon Ultra Moon (Europe) > stuck on black screen

Inazuma Eleven 3 Lightning Bolt (Europe) / Inazuma Eleven 3 - Team Ogre Attacks(EUR)
> don't boot with error
[FATAL] LDR::RO service requested. Command: 000402C2

Pokemon Super Mystery Dungeon (USA) > don't boot with error: 
SDMCArchive::OpenArchive: Failed
SDMCArchive::OpenArchive: Failed
OpenFile failed
OpenFile failed
OpenFile failed
OpenFile failed
SDMCArchive::OpenArchive: Failed
SDMCArchive::OpenArchive: Failed
SDMCArchive::OpenArchive: Failed
SDMCArchive::OpenArchive: Failed
SDMCArchive::OpenArchive: Failed
SDMCArchive::OpenArchive: Failed
SDMCArchive::OpenArchive: Failed
[FATAL] CAM service requested. Command: 00180080

Pokemon Sun (Europe) > stuck on black screen

Mii Maker > crash with error: [FATAL] GetProcessInfo: unimplemented type 1

**Comment by LaReunion974** [comment]
@ArbestRiAgain Hi, can I put some of my test on your compatibility list ?

**Comment by ArbestRiAgain** [comment]
> @ArbestRiAgain Hi, can I put some of my test on your compatibility list ?

You can just press "Request edit access" on the list
