### ISSUE TITLE
Encryption keys don't work

### ISSUE THREAD

**Issue by Adamillo** [wheremyfoodat/Panda3DS#112]
For some reason Panda3ds doesn't accept my aes keys and shows me an error. These keys work in Citra
![image](https://github.com/wheremyfoodat/Panda3DS/assets/45568316/6856477d-7531-4c72-a187-06a3dbe2d901)

**Comment by Adamillo** [comment]
Fixed by including the generator field

**Comment by TCAtrevor** [comment]
How do you get the generator key from your 3DS?

**Comment by wheremyfoodat** [comment]
@TCAtrevor The generator constant is implemented as a regular addition with a constant in hardware and is not a proper key (or easily dumpable) so it's probably okay to share this
 https://github.com/citra-emu/citra/blob/66404a669fe838dce4df93f2b8986e02f748005e/src/core/hw/aes/key.cpp#L30

**Comment by TCAtrevor** [comment]
Thanks!
