### ISSUE TITLE
Error: SDL not configured with OpenGL/GLX support

### ISSUE THREAD

**Issue by rec0veryyy** [wheremyfoodat/Panda3DS#127]
I'm on Ubuntu and when I run `./Alber Mario Kart 7.3ds` I get this error:

`[FATAL] Error creating window: SDL not configured with OpenGL/GLX support.`

Image:

![Screenshot_20230720_140051](https://github.com/wheremyfoodat/Panda3DS/assets/38696644/6d9f0a37-20e9-4d78-a1e3-2d0866e429fe)

Hardware: 
- i5 10400
- 8gb

**Comment by wheremyfoodat** [comment]
I'd recommend trying to build from source if you downloaded the build in releases, haven't figured out how to do portable Linux builds yet

**Comment by rec0veryyy** [comment]
Okay, I just compiled it from source like this, I hope I didn't make a mistake:

```
git clone https://github.com/wheremyfoodat/Panda3DS --recursive
cd Panda3DS && mkdir build && cd build
cmake .. -DCMAKE_BUILD_TYPE=Release -DENABLE_USER_BUILD=ON
```

and now how would it be executed?

**Comment by wheremyfoodat** [comment]
> Okay, I just compiled it from source like this, I hope I didn't make a mistake:
> 
> ```
> git clone https://github.com/wheremyfoodat/Panda3DS --recursive
> cd Panda3DS && mkdir build && cd build
> cmake .. -DCMAKE_BUILD_TYPE=Release -DENABLE_USER_BUILD=ON
> ```
> 
> and now how would it be executed?
> 
> Output:
> 
> ![Screenshot_20230720_141215](https://user-images.githubusercontent.com/38696644/254878969-042d0cba-8c73-4c82-ab11-5f55b38ba395.png)

You have not compiled yet, you configured CMake to prepare for compilation.
Depending on the generator you used (Make, Ninja, etc) you have to invoke the relevant command to actually compile the code. 

if you used make for example, type `make -j2` to compile the code, and when you're done you will have an executable named `Alber` in your build folder

**Comment by rec0veryyy** [comment]
I'll try it later.
Thanks

**Comment by wheremyfoodat** [comment]
> I'm on Ubuntu and when I run `./Alber Mario Kart 7.3ds` I get this error:
> 
> `[FATAL] Error creating window: SDL not configured with OpenGL/GLX support.`
> 
> Image:
> 
> ![Screenshot_20230720_140051](https://user-images.githubusercontent.com/38696644/254876454-6d9f0a37-20e9-4d78-a1e3-2d0866e429fe.png)
> 
> Hardware:
> 
> * i5 10400
> * 8gb

Also, due to how Linux works, you need to do ./Alber "Mario Kart 7.3ds" (note the quotation marks)
If you don't, it will consider `Mario`, `Kart` and `7.3ds` to be different arguments

You can get more support in our discord server if you want to join

**Comment by rec0veryyy** [comment]
> Además, debido a cómo funciona Linux, debe hacer ./Alber "Mario Kart 7.3ds" (tenga en cuenta las comillas). Si no lo hace, considerará `Mario`, `Kart`y `7.3ds`serán argumentos diferentes.

Ah yes, I know that, I just wrote the problem that way and put the quotation marks in it
