### ISSUE TITLE
[CI] Linux builds don't work

### ISSUE THREAD

**Issue by patataofcourse** [wheremyfoodat/Panda3DS#133]
Currently, Linux Panda3DS needs to be self-built, CI builds don't work.

This has been known for a while but I thought it'd be nice to have it in an issue

**Comment by wheremyfoodat** [comment]
Supersedes #127

**Comment by patataofcourse** [comment]
shit sisnt realize that was there lmao

**Comment by wheremyfoodat** [comment]
It's ok, I mean that #133 replaces #127

**Comment by wheremyfoodat** [comment]
Could you try rhe latest CI build to see if the window at least spawns?

**Comment by wheremyfoodat** [comment]
Fixed in #259. Feel free to make separate issues for the AppImage if necessary.
