### ISSUE TITLE
Reverse graphics

### ISSUE THREAD

**Issue by KostaSaizo7** [wheremyfoodat/Panda3DS#166]
Professor Layton and the Miracle Mask has reverse graphics
![image](https://github.com/wheremyfoodat/Panda3DS/assets/39852873/d9dbe8a6-e1c5-43e2-a638-9d448817ad99)

**Comment by wheremyfoodat** [comment]
Same for Yokai Watch 1 & 2

**Comment by KostaSaizo7** [comment]
Fixed by #155 :)
![image](https://github.com/wheremyfoodat/Panda3DS/assets/39852873/7ba727ea-b10a-468d-aeac-2cda6bbc9433) 
![image](https://github.com/wheremyfoodat/Panda3DS/assets/39852873/2520addd-3afe-4b09-bcd9-7d5c05c0a3e8)

**Comment by wheremyfoodat** [comment]
Rhappy!
