### ISSUE TITLE
 New Super Mario Bros. 2 is buggy and low framerate

### ISSUE THREAD

**Issue by LaReunion974** [wheremyfoodat/Panda3DS#184]
Work but with some strange graphical issues and a very low framerate and the console spam:

[Warning] GSP::GPU::TriggerTextureCopy (unimplemented)

![image](https://github.com/wheremyfoodat/Panda3DS/assets/102532446/9456138c-b4ac-48af-818e-e33e14ab2262)

**Comment by wheremyfoodat** [comment]
It doesn't look like you're using a new build for me, looks like you're using the very outdated preview

**Comment by wheremyfoodat** [comment]
You can get a better experience & better compatibility by grabbing our latest build here: https://github.com/wheremyfoodat/Panda3DS/actions/runs/5858332934

**Comment by wheremyfoodat** [comment]
Published a new release to avoid more people getting confused about them, closing this issue as it's a duplicate
