### ISSUE TITLE
[Feature request] Add a Fullscreen mode to the emulator or a resizable window

### ISSUE THREAD

**Issue by LaReunion974** [wheremyfoodat/Panda3DS#190]
Is it possible to make a Fullscreen mode or an argument when we boot a game with a command line to make them boot in Fullscreen or make the Alber window resizable because it's very small

**Comment by wheremyfoodat** [comment]
That is indeed a good feature request and something that should be done

**Comment by LaReunion974** [comment]
It will be a great feature ^^

**Comment by wheremyfoodat** [comment]
Largely
