### ISSUE TITLE
What's the difference between this and Citra?

### ISSUE THREAD

**Issue by larsenv** [wheremyfoodat/Panda3DS#205]
Title.

**Comment by wheremyfoodat** [comment]
https://www.reddit.com/r/emulation/comments/14uxv84/unveiling_panda3ds_a_new_nintendo_3ds_emulator/jrdqcba?utm_source=share&utm_medium=android_app&utm_name=androidcss&utm_term=1&utm_content=2

https://www.reddit.com/r/emulation/comments/15rw69u/announcing_a_new_preview_release_of_panda3ds_a/jwckyig?utm_source=share&utm_medium=android_app&utm_name=androidcss&utm_term=1&utm_content=2

+readme

There's already things this emulator does that Citra doesn't such as the Discord bot support. Also please use the discussion tab for discussions.

**Comment by liuk7071** [comment]
rcow

**Comment by Wunkolo** [comment]
pambda
