### ISSUE TITLE
Using Vulkan API causes purple screen

### ISSUE THREAD

**Issue by JaffaCat** [wheremyfoodat/Panda3DS#210]
The title describes the issue - may be linked to [here](https://github.com/wheremyfoodat/Panda3DS/issues/150) (Baked lights?)
Either that or it doesn't have Vulkan support

**Comment by wheremyfoodat** [comment]
This purple screen is hardcoded on upstream.
The proper Vulkan renderer is being worked on here: https://github.com/Wunkolo/Panda3DS/tree/vulkan-framebuffer
