### ISSUE TITLE
Where is TOTK PS5 Zelda (Sussy Edition)?????

### ISSUE THREAD

**Issue by GhostRain0** [wheremyfoodat/Panda3DS#30]
i had this idea for a 3ds emulator and i think it has a lot of potential. So like what if u emulated totk on 3ds like a port but not really, its on ps5 so its like a ps5 emulator on the 3ds. But i also like among us so do u think u can put a sussy baka in totk? I know u can make it happen

Just to cite my sources this wasn't my idea it was ChatGPT's

**Comment by wheremyfoodat** [comment]
Did it hurt when you fell from paradise?
Because you clearly hit your head somewhere very hard as a baby.
