### ISSUE TITLE
OpenGL 3.1

### ISSUE THREAD

**Issue by sardonix** [wheremyfoodat/Panda3DS#336]
is it possible???

**Comment by wheremyfoodat** [comment]
What GPU are you using? 3.1 is 15 years old and is missing various crucial features.
Chances are your GPU can do above 3.1 if you update your graphics drivers unless it's actually 2 decades old. The current req is 4.1 which almost all in-use GPUs support with updated drivers.

**Comment by Raypuia** [comment]
If you're trying to run it on a machine with a Intel HD 3000 iGPU, you're better off installing Linux on it. (Which funny enough, it supports OpenGL 3.3 unlike the shitty Windows drivers)
