### ISSUE TITLE
Pandroid

### ISSUE THREAD

**Issue by daeklo4** [wheremyfoodat/Panda3DS#342]
Hello, the first version of pandroid in apk arm64 version installs perfectly but it closes when opening said apk, is it because they are tests and is it the first version?

**Comment by daeklo4** [comment]
Wheremyfoodat,Thank you infinitely for all the work you are doing for this great emulator, one question: on Android it will work with vulkan, do you know anything about when mikage will be launched?

**Comment by wheremyfoodat** [comment]
Hello. Pandroid is still early in development and we've been trying to debug why it crashes on real phones the past few days. It should hopefully get fixed soon, but for the time being it only works properly on the AS simulator.
![image-36](https://github.com/wheremyfoodat/Panda3DS/assets/44909372/c425d221-419c-45d6-a82f-59a37a2e796e)

**Comment by daeklo4** [comment]
Muchas gracias por constestar!

**Comment by daeklo4** [comment]
Thanks!
