### ISSUE TITLE
Thanks wheremyfoodat!!!!

### ISSUE THREAD

**Issue by daeklo4** [wheremyfoodat/Panda3DS#367]
Finally , panda3ds is available!, No crash , no issues!!! Thanksss!!!
![Screenshot_2024-01-05-08-41-04-539](https://github.com/wheremyfoodat/Panda3DS/assets/109567065/0a877133-bed3-43ad-9075-65598ee81c10)
![Screenshot_2024-01-05-08-41-52-736](https://github.com/wheremyfoodat/Panda3DS/assets/109567065/c9ffa1ee-6f69-4804-8c26-13243eb112c7)

**Comment by wheremyfoodat** [comment]
![kanna-kamui-kobayashi-san-chi](https://github.com/wheremyfoodat/Panda3DS/assets/44909372/b0c71165-e35c-4f6d-9744-caa599b78747)

**Comment by daeklo4** [comment]
Thanks a lot.

**Comment by hdk2d** [comment]
> Finally , panda3ds is available!, No crash , no issues!!! Thanksss!!!
> ![Screenshot_2024-01-05-08-41-04-539](https://github.com/wheremyfoodat/Panda3DS/assets/109567065/0a877133-bed3-43ad-9075-65598ee81c10)
> ![Screenshot_2024-01-05-08-41-52-736](https://github.com/wheremyfoodat/Panda3DS/assets/109567065/c9ffa1ee-6f69-4804-8c26-13243eb112c7)
> 

How to run game?

**Comment by wheremyfoodat** [comment]
> How to run game?

[pandroid_installation_guide.webm](https://github.com/wheremyfoodat/Panda3DS/assets/44909372/0fe616d5-7060-40e2-bbdb-50c9a3e992e3)

**Comment by SimoneN64** [comment]
> > How to run game?
> 
> pandroid_installation_guide.webm

Thank god, could have never been able to follow otherwise

**Comment by hdk2d** [comment]
> > How to run game?
> 
> [pandroid_installation_guide.webm](https://github.com/wheremyfoodat/Panda3DS/assets/44909372/0fe616d5-7060-40e2-bbdb-50c9a3e992e3)
> 

Won't boot on my Snapdragon 8 Gen 1 device but thanks anyway.
