### ISSUE TITLE
[Bug] Cannot build due to removal of "dynarmic"

### ISSUE THREAD

**Issue by SpikeHD** [wheremyfoodat/Panda3DS#430]
Hi! Wish I could've come across this project sooner, awesome work :)

Unfortunately, as of like, maybe 5 hours ago, the [dynarmic](https://github.com/merryhime/dynarmic) library has been zapped out of existence, which makes it inaccessible as a submodule. I *have* found the Debian Salsa mirror (https://salsa.debian.org/debian/dynarmic, admittedly a little outdated) but I haven't tried it yet due to lack of time.

**Comment by Quackdoc** [comment]
looks like there is a fairly up-to-date fork of dynarmic here https://github.com/lioncash/dynarmic

**Comment by wheremyfoodat** [comment]
Finding a fork is not quitr the problematic part, the reason the submodule hasn't been updated yet is cause I'm still waiting on things with the lawsuit to settle, among some other concerns.

**Comment by wheremyfoodat** [comment]
Fixed thankfully
