### ISSUE TITLE
making the emulator "portable"

### ISSUE THREAD

**Issue by FoxbitDreamtail** [wheremyfoodat/Panda3DS#432]
many emulators support portablizing them(via putting all of the in-use files in the same folder) by placing a blank portable.txt file in the directory, emulators like Dolphin(GC/Wii) and Xenia(XB360) already do this.

**Comment by wheremyfoodat** [comment]
This is done with the UsePortableBuild option in the config.toml file which puts everything in an "Emulator Files" folder next to the program

**Comment by FoxbitDreamtail** [comment]
> UsePortableBuild

would be nice if this was documented or mentioned in the github readme.
