### ISSUE TITLE
Add support for "installing" Cia's

### ISSUE THREAD

**Issue by FoxbitDreamtail** [wheremyfoodat/Panda3DS#433]
all the 3DS files I have dumped from my 3ds when it was working was in .cia format, cia support needs to be added to allow me to play my roms, kinda like how citra(RIP) used to do.

**Comment by Adamillo** [comment]
Panda3ds already supports loading cia. It's just that it can't install it at the moment

**Comment by wheremyfoodat** [comment]
I'll supersede this with #434, please don't refer to unlawful activities when submitting issues

**Comment by FoxbitDreamtail** [comment]
> I'll supersede this with #434, please don't refer to illegal activities when submitting issues

but, I legally dumped these files, no illegal activity here!

**Comment by notprogramminggames** [comment]
> > I'll supersede this with #434, please don't refer to illegal activities when submitting issues
> 
> but, I legally dumped these files, no illegal activity here!

In the wrong context it can seem as if they were illegally obtained.

**Comment by FoxbitDreamtail** [comment]
Okay? Contacts is a pain to navigate in today's modern age anyway, plus
pirating 3DS games is a real pain anyway unless you have the original
hardware where you can use hshop, in which case you would still need to
dump it from the original 3DS hardware proving that you owned a 3DS and
therefore would have bought it had the software been available to you, need
I remind everyone here that the last official way to purchase Nintendo 3DS
and Wii U software with discontinued last year in May, it's pretty damn
dead. And this year they're going to cut all internet ties with the 3DS and
Wii U so I am pretty sure that these systems are literally on life support,
to say that piracy is an illegitimate way to obtain these titles is dubious
at best considering how much the second hand scalping market would cost for
each physical copy, assuming that a physical copy of said game was even
distributed. For a lot of people it is not financially feasible to go on
eBay and pay a couple thousand dollars just for a copy of Mario Maker for
Wii U or 3DS, it is financially unfeasible to go out and purchase Mario
kart 8 to realize that you don't have any of the DLCs for it and will never
be able to buy any of the DLCs for it, piracy equals preservation in most
cases, this is something that Nintendo and many emulator developers should
understand by now. I'm not trying to speak for absolutely everyone here nor
am I trying to defend pirates or people who would never have purchased said
software (I definitely would because I'm one of the poor suckers who bought
Minecraft for the 3DS at full price) but I damn sure know that unless a way
to obtain software is presented for people to be able to continue to enjoy
software long beyond its expiration date it will fade into obscurity and
the pieces of software will never be able to be enjoyed by anyone under any
circumstances ever again.

**Comment by Adamillo** [comment]
It does not matter if the games or DLC are no longer legally available to purchase. The US copyright laws say that it's still illegal to pirate games or DLC regardless if they're available or not. I wish that this wasn't the case but that's how it works sadly, and we have to abide these laws

**Comment by FoxbitDreamtail** [comment]
> It does not matter if the games or DLC are no longer legally available to purchase. The US copyright laws say that it's still illegal to pirate games or DLC regardless if they're available to purchase or not. I wish that this wasn't the case but that's how it works sadly, and we have to abide these laws

Regardless the content I ripped from my 3DS before it stopped functioning it was mine that I had legally purchased, locking people behind this barrier just because you can't verify something is not something that an emulator should do. The whole point of emulators is preservation is it not? The emulator itself shouldn't care where the ROMs came from however all that the emulator should care about is how to run it. That's the way in which all emulators historically have functions now if Nintendo were to release a desktop emulator where you can purchase ROMs legally then emulators like yours would have no reason to exist, but that's just my two cents on the matter. I'm willing to drop all conversation about this so that no more issues occur.
