### ISSUE TITLE
My First Time Opening Panda3DS - An Empty "Alber" Folder Appeared

### ISSUE THREAD

**Issue by P0W3** [wheremyfoodat/Panda3DS#440]
I opened Panda3DS for the first time, and all I saw was nothing but an empty "Alber" folder. There are no issues to the Panda3DS application.

![image](https://github.com/wheremyfoodat/Panda3DS/assets/18279115/61d54fe5-786e-4110-9427-3c5cef7f674d)

**Comment by Adamillo** [comment]
It seems like your anti virus deleted it. Try adding it to the exclusion list

**Comment by P0W3** [comment]
Moreover...

![image](https://github.com/wheremyfoodat/Panda3DS/assets/18279115/2f6c0eaf-2d06-4b3b-b835-e4ee6e3e586c)
![image](https://github.com/wheremyfoodat/Panda3DS/assets/18279115/bc50f967-d3ef-40b2-b999-1aeb98f2d863)

**Comment by wheremyfoodat** [comment]
That is indeed a window

**Comment by P0W3** [comment]
None of the "Alber" files got erased. I only opened the "Alber.exe" file. What is needed in the "C:\Users\USERNAME\AppData\Roaming\Alber" directory?

![image](https://github.com/wheremyfoodat/Panda3DS/assets/18279115/6901800c-80b9-4788-9ab0-805e7f219e55)

**Comment by wheremyfoodat** [comment]
That is where saves and other emulator data is stored

**Comment by wheremyfoodat** [comment]
> Moreover...
> 
> ![image](https://private-user-images.githubusercontent.com/18279115/310516933-2f6c0eaf-2d06-4b3b-b835-e4ee6e3e586c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3MzI5NjksIm5iZiI6MTcwOTczMjY2OSwicGF0aCI6Ii8xODI3OTExNS8zMTA1MTY5MzMtMmY2YzBlYWYtMmQwNi00YjNiLWI4MzUtZTRlZTZlM2U1ODZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA2VDEzNDQyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU3Y2E1OGQyY2UxMTk3ZTZlNGZlZjYzZTNiYzgzNjc2MWFkOGRjMTc2YmY2NGZhZDljNDIxMmUwM2Q5MmFmZTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MJbxsCtFDCSp4_7KPDZUxvg6HWbL-GDVQrS7A7RrhEY) ![image](https://private-user-images.githubusercontent.com/18279115/310517370-bc50f967-d3ef-40b2-b999-1aeb98f2d863.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3MzI5NjksIm5iZiI6MTcwOTczMjY2OSwicGF0aCI6Ii8xODI3OTExNS8zMTA1MTczNzAtYmM1MGY5NjctZDNlZi00MGIyLWI5OTktMWFlYjk4ZjJkODYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA2VDEzNDQyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEwMjY0MDA4MzZjY2M2OGQ1MmUxMWNmNGY3NDg4NjAyMTA3YTFlZWU3YzAwNGU2ZWNlNWRjMzk5OWU5OTNhYmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3wV-x5LDvfv_WbTkR9GYg_H7u1x72dyuUX9jc1yOkNQ)

If you're confused about the second window, it's just where logs and such get printed (in this case some GPU info and information about the acquired OpenGL context).

Anyways, closing this since there's no apparent issue here now.
