### ISSUE TITLE
Website FAQ

### ISSUE THREAD

**Issue by CatsLover2006** [wheremyfoodat/Panda3DS#443]
![IMG_0672](https://github.com/wheremyfoodat/Panda3DS/assets/28163018/0f93b420-3ba9-437a-b03a-ba28f1c689a2)

**Comment by wheremyfoodat** [comment]
Hello could you please move this issue to the website's repository
https://github.com/Panda3DS-emu/panda3ds-dot-com

**Comment by CatsLover2006** [comment]
Done; [it’s issue 4 over there](https://github.com/Panda3DS-emu/panda3ds-dot-com/issues/4).

**Comment by wheremyfoodat** [comment]
Thank you
