### ISSUE TITLE
Gbc

### ISSUE THREAD

**Issue by eepykami** [wheremyfoodat/Panda3DS#478]

**Comment by wheremyfoodat** [comment]
For GBC emulation, please submit issues to https://github.com/PSI-Rockin/Corgi3DS
Also if you want to play Pokemon XY/ORAS/SM/USUM on Panda3DS, make sure to join the Corgi3DS discord (https://discord.com/invite/xFSDSeM) and @ the "PSI" person

**Comment by PSI-Rockin** [comment]
Hello, GBC emulation is already provided in Panda3DS. You must simply use a quantum computer to construct a new reality in which this possibility has occurred. Users that use Panda3DS are expected to have quantum computers due to the emulator's lack of optimization at this time.

**Comment by eepykami** [comment]
> Hello, GBC emulation is already provided in Panda3DS. You must simply use a quantum computer to construct a new reality in which this possibility has occurred. Users that use Panda3DS are expected to have quantum computers due to the emulator's lack of optimization at this time.

This worked for me, thank you.

**Comment by wheremyfoodat** [comment]
> Hello, GBC emulation is already provided in Panda3DS. You must simply use a quantum computer to construct a new reality in which this possibility has occurred. Users that use Panda3DS are expected to have quantum computers due to the emulator's lack of optimization at this time.

Hello, please do not spread misinformation if you are not a developer or not experienced with emulation. Consider deleting your Github account and making a Club Penguin one instead, you're more likely to find people of your caliber there. XO

**Comment by eepykami** [comment]
huge github pr drama

**Comment by PSI-Rockin** [comment]
> > Hello, GBC emulation is already provided in Panda3DS. You must simply use a quantum computer to construct a new reality in which this possibility has occurred. Users that use Panda3DS are expected to have quantum computers due to the emulator's lack of optimization at this time.
> 
> Hello, please do not spread misinformation if you are not a developer or experienced with emulation. Consider deleting your Github account and making a Club Penguin one instead, you're more likely to find people of your caliber there. XO

Wait you're a developer? Can you make a game for me? I'll pay you $500

**Comment by wheremyfoodat** [comment]
> > > Hello, GBC emulation is already provided in Panda3DS. You must simply use a quantum computer to construct a new reality in which this possibility has occurred. Users that use Panda3DS are expected to have quantum computers due to the emulator's lack of optimization at this time.
> > 
> > 
> > Hello, please do not spread misinformation if you are not a developer or experienced with emulation. Consider deleting your Github account and making a Club Penguin one instead, you're more likely to find people of your caliber there. XO
> 
> Wait you're a developer? Can you make a game for me? I'll pay you $500

Hello please give me $500 in the donation links on the repo and I will send you a complete game
