### ISSUE TITLE
blue screen super mario 3d land

### ISSUE THREAD

**Issue by omagadsamsa** [wheremyfoodat/Panda3DS#513]
then crash. Huawei U6 2018 phone, open GL Es 3.0, if you add software to the emulator it can fix it

**Comment by wheremyfoodat** [comment]
GLES 3.0 is not currently supported

**Comment by omagadsamsa** [comment]
> GLES 3.0 is not currently supported

add software???

**Comment by sylvieee-iot** [comment]
I am soft but my ware hard

**Comment by eepykami** [comment]
add software???
