### ISSUE TITLE
Who is Alber?

### ISSUE THREAD

**Issue by fleroviux** [wheremyfoodat/Panda3DS#52]
I thought the emulator was called Panda3DS. But the window title mentions Alber? Who is Alber? And what is he doing on my PC?

**Comment by wheremyfoodat** [comment]
Please don't disrespect Albert and properly refer to him as "His Majesty" from now on. You would make him very sad and that's actually considered treason.

**Comment by TheMasterCoders** [comment]
???

**Comment by UDXS** [comment]
Long live Alber

**Comment by wheremyfoodat** [comment]
Long live Alber

**Comment by fleroviux** [comment]
Long live Alber

**Comment by GPUCode** [comment]
Alber is the panda friends we made along the way

**Comment by SimoneN64** [comment]
alber

**Comment by LaReunion974** [comment]
Alber 🖖

**Comment by wheremyfoodat** [comment]
ALBER

**Comment by noumidev** [comment]
alber

**Comment by Wolfyxon** [comment]
I need context

**Comment by eepykami** [comment]
> I need context

alber
