### ISSUE TITLE
HI, need information about this emulator

### ISSUE THREAD

**Issue by daeklo4** [wheremyfoodat/Panda3DS#601]
Hi, wheremyfoodat you emulator is very good,what are the actual status of this version on android specifically, if you have a free time, tell me, check the photo
![Screenshot_2024-09-29-08-07-40-393](https://github.com/user-attachments/assets/d241295a-4878-4050-8f84-8d203332682f)
![Screenshot_2024-09-29-08-08-26-587](https://github.com/user-attachments/assets/48411195-0fef-484d-a2de-cf3990f85870)

**Comment by wheremyfoodat** [comment]
If you mean the status of the "fast" version, this version became official last week and you can now get it from www.panda3ds.com
