### ISSUE TITLE
config.toml does not exist on MacOS builds

### ISSUE THREAD

**Issue by otherlego** [wheremyfoodat/Panda3DS#607]
When you run Alber.app on MacOS there is no config file created. It doesn't show up in Application Support, nor does it show up in the directory it ran in. I don't know why this happens. If you need any more information let me know.

**Comment by tr33m0rt3** [comment]
Is there any way  to change settings on MacOS? I would like to enable audio

**Comment by otherlego** [comment]
i dont think so

**Comment by tr33m0rt3** [comment]
Word, hopefully in the future. Thx for replying

**Comment by wheremyfoodat** [comment]
Fixed
