### ISSUE TITLE
Steam deck build error: SDL NOT CONFIGURED FOR OPENGL

### ISSUE THREAD

**Issue by quimodotcom** [wheremyfoodat/Panda3DS#610]
The classic SDL NOT CONFIGURED error has returned with latest source code building on steam deck.

Originally I had plenty of errors with cmake however after reinstalling tons of packages, I finally made it and built the app, only to launch and get the famous SDL NOT CONFIGURED. tried both vulkan on and off in cmake.

Can give the exact commands used later today.

**Comment by wheremyfoodat** [comment]
You're probably missing some of the mesa/gl packages. If you look at the Linux workflows in the .github folder, you can see exactly which packages CI installs to compile the emulator.
