### ISSUE TITLE
Ps vita suport?

### ISSUE THREAD

**Issue by Sal-gamer** [wheremyfoodat/Panda3DS#614]
https://github.com/vita-nuova/bounties/issues/117

**Comment by wheremyfoodat** [comment]
Not really

**Comment by huckleberrypie** [comment]
Good luck with that. We barely have working DS emulation on the Vita, let alone something as powerful as the 3DS.

**Comment by Sal-gamer** [comment]
> Boa sorte com isso. Mal temos emulação de DS funcionando no Vita, muito menos algo tão poderoso quanto o 3DS.

the Nintendo DS does NOT run well on the vita for the simple reason that its cpu is not compatible with the cpu of the ps vita, having to be emulated, and the ds emulation in arm32 is more complicated than arm64, with most emulators supporting only arm64, but with drastick being open sorce, it would be possible for the PS Vita to run the Nintendo DS smoothly as drastick is optimized for arm32 with little memory usage. As for 3ds, it is compatible with the PS Vita's cpu, so it wouldn't really be an emulation but rather natively the 3ds instructions with some emulated things, there's a discussion about this that I put next to the problem.

**Comment by wheremyfoodat** [comment]
CPU emulation is the least problematic part in this case, yes. GPU, DSP, etc emulation on the other hand are huge problems and getting respectable performance on a Vita borders on impossible.

**Comment by eepykami** [comment]
shadps4 on vita when

**Comment by Sal-gamer** [comment]
> Sim, a emulação de CPU é a parte menos problemática neste caso. Por outro lado, a emulação de GPU, DSP, etc. são problemas enormes e obter um desempenho respeitável em um Vita beira o impossível.

"The distance between madness and genius It is measured only by success. " Something ALMOST impossible, doesn't mean impossible, it just hasn't been done yet, as soon as something like this is done, it will be like a miracle if accomplished. But I'm not going to prolong the discussion, thank you for answering me.

**Comment by profi200** [comment]
Smart sounding quotes won't change the situation.  The only way to even get something remotely playable would be a hypervisor approach where the game code runs native and and services/hardware are emulated. The Vita simply doesn't have enough power to overcome the overhead by the emulated services and GPU. It's only a little faster than the 3DS itself.
