### ISSUE TITLE
building on linux ARM64 

### ISSUE THREAD

**Issue by Sillylittleguy1** [wheremyfoodat/Panda3DS#623]
I have followed the steps up to building, and i am encountering errors. 

`user@shimboot-corsola:~/Panda3DS/build$ cmake .. -DCMAKE_BUILD_TYPE=Release -DENABLE_USER_BUILD=ON  # Set up compilers etc here if you'd like
-- The C compiler identification is GNU 12.2.0
-- The CXX compiler identification is GNU 12.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Git: /usr/bin/git (found version "2.39.5") 
CMake Error at CMakeLists.txt:137 (add_subdirectory):
  The source directory

    /home/user/Panda3DS/third_party/discord-rpc

  does not contain a CMakeLists.txt file.

CMake Error at CMakeLists.txt:146 (add_subdirectory):
  The source directory

    /home/user/Panda3DS/third_party/SDL2

  does not contain a CMakeLists.txt file.

CMake Error at CMakeLists.txt:150 (add_subdirectory):
  The source directory

    /home/user/Panda3DS/third_party/fmt

  does not contain a CMakeLists.txt file.

CMake Error at CMakeLists.txt:151 (add_subdirectory):
  The source directory

    /home/user/Panda3DS/third_party/toml11

  does not contain a CMakeLists.txt file.

CMake Error at CMakeLists.txt:158 (add_subdirectory):
  The source directory

    /home/user/Panda3DS/third_party/cmrc

  does not contain a CMakeLists.txt file.

-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
CMake Error at CMakeLists.txt:179 (add_subdirectory):
  The source directory

    /home/user/Panda3DS/third_party/LuaJIT

  does not contain a CMakeLists.txt file.

CMake Error at CMakeLists.txt:181 (set_target_properties):
  set_target_properties Can not find target to add properties to: luajit

CMake Error at CMakeLists.txt:207 (add_subdirectory):
  The source directory

    /home/user/Panda3DS/third_party/oaknut

  does not contain a CMakeLists.txt file.

-- Found RenderDoc: third_party/renderdoc (Required is at least version "1.6.0") 
CMake Error at CMakeLists.txt:231 (add_subdirectory):
  The source directory

    /home/user/Panda3DS/third_party/dynarmic

  does not contain a CMakeLists.txt file.

CMake Error at CMakeLists.txt:237 (add_subdirectory):
  The source directory

    /home/user/Panda3DS/third_party/teakra

  does not contain a CMakeLists.txt file.

CMake Error at CMakeLists.txt:238 (add_subdirectory):
  The source directory

    /home/user/Panda3DS/third_party/fdk-aac

  does not contain a CMakeLists.txt file.

CMake Error at CMakeLists.txt:243 (add_subdirectory):
  The source directory

    /home/user/Panda3DS/third_party/capstone

  does not contain a CMakeLists.txt file.

CMake Error at CMakeLists.txt:332 (cmrc_add_resource_library):
  Unknown CMake command "cmrc_add_resource_library".

-- Configuring incomplete, errors occurred!
See also "/home/user/Panda3DS/build/CMakeFiles/CMakeOutput.log".
`
is this because im on ARM or i screwed up somewhere in the steps?

**Comment by wheremyfoodat** [comment]
You did not clone with the recursive flag, so all your submodules are missing

**Comment by Sillylittleguy1** [comment]
^ thank you magic man
