### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by daeklo4** [wheremyfoodat/Panda3DS#644]
Hi, the latest pandroid version crash on my phone before not, can help me?.Please
[current.txt](https://github.com/user-attachments/files/17882187/current.txt)

**Comment by wheremyfoodat** [comment]
What game are you trying to run...?

**Comment by daeklo4** [comment]
Pokemon omega ruby

**Comment by wheremyfoodat** [comment]
It seems like the game is crashing inside the PowerVR GPU drivers while trying to compile a shader. If this didn't happen before then it's possible your phone manufacturer pushed a broken update.

**Comment by daeklo4** [comment]
> What game are you trying to run...?

Pokemon omega ruby new,super mario bros 2

**Comment by daeklo4** [comment]
> It seems like the game is crashing inside the PowerVR GPU drivers while trying to compile a shader. If this didn't happen before then it's possible your phone manufacturer pushed a broken update.

Yes, in the other pandroid update not crash this games, only in actual fast version 😭, for example citra mmj and mandarine emu not crash when using opengl

**Comment by daeklo4** [comment]
> It seems like the game is crashing inside the PowerVR GPU drivers while trying to compile a shader. If this didn't happen before then it's possible your phone manufacturer pushed a broken update.

Thanks for answering my issue
