### ISSUE TITLE
Review this please!

### ISSUE THREAD

**Issue by daeklo4** [wheremyfoodat/Panda3DS#653]
When attemp to initialize a game in pandroid like pokemon ORAS, NSMB2 etc the emulator crash
[current.txt](https://github.com/user-attachments/files/17966816/current.txt)
[last.txt](https://github.com/user-attachments/files/17966817/last.txt)
![Screenshot_2024-11-30-15-20-50-341](https://github.com/user-attachments/assets/a9f29bbe-7826-4f21-87c0-8b54ff337ba5)
![Uploading Screenshot_2024-11-30-15-21-17-868.jpg…]()

**Comment by daeklo4** [comment]
@wheremyfoodat hi I appreciate a lot you hardwork for create this emulator, i follow this everyday, when attemp initialize the pokemon omega ruby on pandroid the emulator crash after the lenguage selection

**Comment by daeklo4** [comment]
![Screenshot_2024-11-30-15-21-17-868](https://github.com/user-attachments/assets/2461f6b6-6f86-4d31-873b-dbb6461a3352)

**Comment by wheremyfoodat** [comment]
Sadly for this it's probably not feasible to fix this on the emulator side, and will require your GPU manufacturer to update their drivers

**Comment by daeklo4** [comment]
> Sadly for this it's probably not feasible to fix this on the emulator side, and will require your GPU manufacturer to update their drivers

@wheremyfoodat thanks a lot,Thank you very much, apparently that's what it is with that oor game with pandroid terraria if it works, do you know the citra mmj emulator

**Comment by daeklo4** [comment]
![Screenshot_2024-11-30-15-39-17-246](https://github.com/user-attachments/assets/806ef275-8781-4f86-bd0e-59f727a15cb5)
