### ISSUE TITLE
Raspberry Pi 5, has vulkan but not OpenGL

### ISSUE THREAD

**Issue by retropieuser** [wheremyfoodat/Panda3DS#690]
I've noticed on the Pi 5 if I try to run panda3DS I get an error for OpenGL that crashes the system as it's not openGL 4 

`Parameters: 
Executing: /opt/retropie/ports/Panda3DS/Alber
Welcome to Panda3DS v0.9!
[FATAL] OpenGL context creation failed: Could not create EGL context (call to eglCreateContext failed, reporting an error of EGL_BAD_MATCH)
`

I edited the config to attempt to use the vulkan renderer instead as this is supported on Pi 5. But I keep getting the above OpenGL Error, even though I've set the renderer.
 
Testing on my Mac I notice that the program seems to attempt openGL and then attempt vulkan if you've changed the config

`Created a OpenGL context
GL_VENDOR: Apple
GL_RENDERER: Apple M1
GL_VERSION: 4.1 Metal - 88.1
GL_SHADING_LANGUAGE_VERSION: 4.10
NCSD is supposedly encrypted but not actually encrypted
Stack size: 00004000
BSS size: 00024AC0
ExeFS offset: 00000C00, size: 001DB400 (Offset in file = 00004C00)
File 0. Name: .code, Size: 00111554, Offset: 00000000
File 1. Name: banner, Size: 000C4210, Offset: 00111600
File 2. Name: icon, Size: 000036C0, Offset: 001D5A00
File 3. Name: logo, Size: 00002000, Offset: 001D9200
RomFS offset: 001E0000, size: 00F05000
Stack size: 00000000
BSS size: 00000000
RomFS offset: 010E6000, size: 00059000
Text address = 00100000, size = 00186FAC
Rodata address = 00287000, size = 00029F78
Data address = 002B1000, size = 00012FC0
Stack size: 00004000
Console region autodetected to: North America
Welcome to Panda3DS v!
[FATAL] Vulkan on Qt is currently WIP, try the SDL frontend instead!
QObject::killTimer: Timers cannot be stopped from another thread
QObject::~QObject: Timers cannot be stopped from another thread`

Is there a means to use vulkan as a fallback or to take preference over OpenGL? As it looks like OpenGL is taking preference

**Comment by wheremyfoodat** [comment]
There's ongoing work to fix RPi 5 support since it doesn't support desktop GL (and instead wants you to use OpenGL ES).

Vulkan renderer sadly isn't finished, but with some work the OpenGL ES renderer can largely run fullspeed on RPi 5.

**Comment by wheremyfoodat** [comment]
OK, Raspberry Pi 5 should work now

**Comment by retropieuser** [comment]
> OK, Raspberry Pi 5 should work now

Tested on RetroPie built on Raspberry Pi OS Lite without a desktop and it works, happily played a bit of Pushmo. That's some awesome work thank you

**Comment by wheremyfoodat** [comment]
Awesome 🥰

**Comment by guybrushthre** [comment]
hey there! I'm using Batocera on Rpi5. Any chance you can share some more information on how to get it working?
