### ISSUE TITLE
Seg fault after compilation

### ISSUE THREAD

**Issue by Blad3forc3** [wheremyfoodat/Panda3DS#691]
After compiling the Qt version (everything went ok) I get a seg fault on Kubuntu 24.04

Unhandled SIGSEGV at rip 0x000079899b9d67a8
Segmentation fault (core dumped)

**Comment by DaniElectra** [comment]
Try launching it under XWayland, Wayland currently doesn't work on the Qt version: https://github.com/wheremyfoodat/Panda3DS/issues/586

**Comment by wheremyfoodat** [comment]
@DaniElectra has most likely fixed this in #699, let us know if the issue persists though
