### ISSUE TITLE
High RAM usage Super Mario 3D Land (Android)

### ISSUE THREAD

**Issue by newuser9290** [wheremyfoodat/Panda3DS#704]
High RAM usage on most games is around 6GB-9GB depending on game. Again log to file option after launching game closing game, then closing app and reopening yields nothing, screenshot for reference ![Screenshot_20241230_082214_pandroid.png](https://github.com/user-attachments/assets/523f49ba-752e-4090-aeb2-da6537945108)

![Screenshot_20241230_082452_Cx File Explorer.png](https://github.com/user-attachments/assets/e865ec37-6c61-472c-933b-89e627e6c269)

![Screenshot_20241230_082649_pandroid.png](https://github.com/user-attachments/assets/03123a80-9a7f-4de0-9c5d-b4fca463c5c8)

**Comment by wheremyfoodat** [comment]
Yes, this is indeed system RAM usage
