### ISSUE TITLE
Rhythm Heaven Megamix and Rhythm Paradise Megamix hang on black screen

### ISSUE THREAD

**Issue by wheremyfoodat** [wheremyfoodat/Panda3DS#88]
I can get Rhythm Heaven Megamix (USA) to go in-game by adding a hack to the threading system. Seems like the games might be broken due to a thread scheduler issue that causes an important thread to never run. Pictures of the title screen and hack used to get it below
![image](https://github.com/wheremyfoodat/Panda3DS/assets/44909372/db58c2ca-b024-4b4c-9130-2eab1bff4aad)
![image](https://github.com/wheremyfoodat/Panda3DS/assets/44909372/353df87d-7a33-47d1-9236-4abcbf2d2a25)

**Comment by patataofcourse** [comment]
fyi the entire game runs on a music/bpm-based engine (which leads to some buggery for example when you open rosalina on luma3ds), so it might be related to that

**Comment by EstexNT** [comment]
It looks like the main game thread (index 0) gets constantly(every frame?) sent into a second-long Sleep at some point during save file initialization (at 0028c020)

**Comment by wheremyfoodat** [comment]
As @PSI-Rockin brought to my attention, there's a couple more things that can preempt the kernel thread scheduler, such as a thread waking up from sleep or any timer interrupt. This is not handled yet and may be the cause of this bug. Will need a proper timing system before investigating.

**Comment by wheremyfoodat** [comment]
Forgot to close this.
Fixed in #152 (Megamix) and #180 (Paradise)
